using Business;
using DocumentFormat.OpenXml.Presentation;
using DocumentFormat.OpenXml.Wordprocessing;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Interop;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace GCRM
{

	public partial class FCitizenNetworkData : Form
	{
		DataSet DSCitizenNetwork;
		DataTable DTMembers;
		DataTable DTRoles;

		FAccessMode Mode;
		int Id;
		TCitizen LeadCitizen;

		FCitizenNetworkMemberData MemberDlg;
		FCitizenNetworkRoleData RoleDlg;

		public FCitizenNetworkData()
		{
			InitializeComponent();

			LeadCitizen = new TCitizen();

			// create the datasource
			DSCitizenNetwork = new DataSet("DSCitizenNetwork");

			// create the members datatable
			DTMembers = new DataTable("DTMembers");

			DataColumn col_members_id = DTMembers.Columns.Add("id", typeof(int));
			col_members_id.AutoIncrement = true;
			col_members_id.AutoIncrementSeed = 1;
			
			DTMembers.Columns.Add("citizennetwork_id", typeof(int));
			DTMembers.Columns.Add("citizen_id", typeof(int));
			DTMembers.Columns.Add("role_id", typeof(int));
			DTMembers.Columns.Add("parent_member_id", typeof(int));
			DTMembers.Columns.Add("citizen_name", typeof(string));
			DTMembers.Columns.Add("role_name", typeof(string));
			DSCitizenNetwork.Tables.Add(DTMembers);

			// initialize members datagrid
			DataGridUtilities.AddColumn(DataGridMembers, "colId", "Miembro Id", "id", false);
			DataGridUtilities.AddColumn(DataGridMembers, "colCitizenNetworkId", "Estructura Id", "citizennetwork_id", false);
			DataGridUtilities.AddColumn(DataGridMembers, "colCitizenId", "Ciudadano Id", "citizen_id", false);
			DataGridUtilities.AddColumn(DataGridMembers, "colRoleId", "Rol Id", "role_id", false);
			DataGridUtilities.AddColumn(DataGridMembers, "colParentMemberId", "Miembro Padre", "parent_member_id", false);

			int display_index = 0;

			DataGridUtilities.AddColumn(DataGridMembers, "colCitizenName", "Nombre", "citizen_name", true, display_index++, 100, 100, DataGridViewAutoSizeColumnMode.AllCells);
			DataGridUtilities.AddColumn(DataGridMembers, "colRoleName", "Rol", "role_name", true, display_index++, 50, 50, DataGridViewAutoSizeColumnMode.Fill);

			// bind the members datagrid
			DataGridMembers.DataSource = DSCitizenNetwork;
			DataGridMembers.DataMember = "DTMembers";

			// create the roles datatable
			DTRoles = new DataTable("DTRoles");

			DataColumn col_roles_id = DTRoles.Columns.Add("id", typeof(int));
			col_roles_id.AutoIncrement = true;
			col_roles_id.AutoIncrementSeed = 1;

			DTRoles.Columns.Add("citizennetwork_id", typeof(int));
			DTRoles.Columns.Add("name", typeof(string));
			DTRoles.Columns.Add("description", typeof(string));
			DSCitizenNetwork.Tables.Add(DTRoles);

			// initialize roles datagrid
			DataGridUtilities.AddColumn(DataGridRoles, "colId", "Id", "id", false);
			DataGridUtilities.AddColumn(DataGridRoles, "colCitizenNetworkId", "EstructuraId", "citizennetwork_id", false);

			display_index = 0;

			DataGridUtilities.AddColumn(DataGridRoles, "colName", "Nombre", "name", true, display_index++, 100, 100, DataGridViewAutoSizeColumnMode.AllCells);
			DataGridUtilities.AddColumn(DataGridRoles, "colDescription", "Descripción", "description", true, display_index++, 100, 100, DataGridViewAutoSizeColumnMode.Fill);

			// bind the roles datagrid
			DataGridRoles.DataSource = DSCitizenNetwork;
			DataGridRoles.DataMember = "DTRoles";

			// member dialog
			MemberDlg = new FCitizenNetworkMemberData(DTRoles);

			// roles dialog
			RoleDlg = new FCitizenNetworkRoleData();

			// hide structure view by default
			BShowTree.Checked = false;
			BShowTree_Click(this, null);
		}

		public void SetAccessMode(FAccessMode mode)
		{
			Mode = mode;
		}

		public void SetId(int id)
		{
			using (new CursorWait())
			{
				Id = id;

				TCitizenNetwork network;

				Error error = CitizenNetworksHandler.GetCitizenNetworkById(Id, out network);

				if (error != 0)
				{
					Utilities.ShowErrorDialog(error);
					return;
				}

				// fill general data	
				TextBoxName.Text = network.Name;
				TextBoxDescription.Text = network.Description;
				TextBoxLeadCitizen.Text = $"{network.LeadCitizen.Name} {network.LeadCitizen.PaternalName} {network.LeadCitizen.MaternalName}";
				LLeadCitizenInfo.Text = $"Tel. {network.LeadCitizen.Phone} Cel. {network.LeadCitizen.Cellphone}";

				LeadCitizen = network.LeadCitizen;

				Text = $"Estructura - {network.Name}";

				// fill roles
				DTRoles.BeginLoadData();
				DTRoles.Clear();

				foreach (TCitizenNetworkRole role in network.Roles)
				{
					DataRow row = DTRoles.NewRow();

					int new_role_id = (int)row["id"]; // this value is autogenerated by DataTable column as autoincrement = true

					row["citizennetwork_id"] = role.CitizenNetworkId;
					row["name"] = role.Name;
					row["description"] = role.Description;

					DTRoles.Rows.Add(row);

					// ugly... asign the correct (generated on frontend) id for the member

					foreach (TCitizenNetworkMember member in network.Members)
					{
						if (member.Role.Id == role.Id)
						{
							member.Role.Id = new_role_id;
						}
					}

					role.Id = new_role_id;
				}

				DTRoles.EndLoadData();

				// fill members
				DTMembers.BeginLoadData();
				DTMembers.Clear();

				foreach (TCitizenNetworkMember member in network.Members)
				{
					DataRow row = DTMembers.NewRow();

					row["id"] = member.Id;
					row["citizennetwork_id"] = member.CitizenNetworkId;
					row["citizen_id"] = member.Citizen.Id;
					row["parent_member_id"] = member.ParentMemberId;
					row["role_id"] = member.Role.Id;
					row["citizen_name"] = member.Citizen.GetFullName();
					row["role_name"] = member.Role.Name;

					DTMembers.Rows.Add(row);
				}

				DTMembers.EndLoadData();

				RefreshMembersStructure();
			}
		}

		private void RefreshMembersStructure()
		{
			using (new CursorWait())
			{
				TreeViewMembers.BeginUpdate();
				TreeViewMembers.Nodes.Clear();

				// first node of the tree is the lead
				TreeNode root_node = new TreeNode(LeadCitizen.GetFullName());

				TreeViewMembers.Nodes.Add(root_node);

				// second level are all children of this
				foreach (DataRow row in DTMembers.Rows)
				{
					if ((int)row["parent_member_id"] == 0)
					{
						TreeNode child_node = new TreeNode((string)row["citizen_name"]);

						child_node.Tag = new TCitizenNetworkMember()
						{
							Id = (int)row["id"],
							ParentMemberId = (int)row["parent_member_id"]
						};

						root_node.Nodes.Add(child_node);

						// then all others members
						PopulateTreeNode(ref root_node, ((TCitizenNetworkMember)child_node.Tag).Id);
					}
				}

				TreeViewMembers.EndUpdate();

				TreeViewMembers.ExpandAll();
			}
		}

		public void PopulateTreeNode(ref TreeNode node, int id)
		{
			foreach (DataRow row in DTMembers.Rows)
			{
				if ((int)row["parent_member_id"] == id)
				{
					TreeNode child_node = new TreeNode((string)row["citizen_name"]);

					child_node.Tag = new TCitizenNetworkMember()
					{
						Id = (int)row["id"],
						ParentMemberId = (int)row["parent_member_id"]
					};

					node.Nodes.Add(child_node);

					PopulateTreeNode(ref child_node, (int)row["id"]);
				}
			}
		}

		private bool ValidateInput()
		{
			return true;
		}

		private void BAccept_Click(object sender, EventArgs e)
		{
			if (ValidateInput() == false)
			{
				return;
			}

			using (new CursorWait())
			{
				TCitizenNetwork network = new TCitizenNetwork();

				// general data
				network.Id = Id;
				network.Name = TextBoxName.Text.Trim();
				network.Description = TextBoxDescription.Text.Trim();
				network.LeadCitizen.Id = LeadCitizen.Id;

				// roles
				foreach (DataRow row in DTRoles.Rows)
				{
					TCitizenNetworkRole role = new TCitizenNetworkRole();

					role.Id = (int)row["id"];
					role.CitizenNetworkId = Id;
					role.Name = (string)row["name"];
					role.Description = (string)row["description"];

					network.Roles.Add(role);
				}

				// members
				foreach (DataRow row in DTMembers.Rows)
				{
					TCitizenNetworkMember member = new TCitizenNetworkMember();

					member.Id = (int)row["id"];
					member.CitizenNetworkId = Id;
					member.Citizen.Id = (int)row["citizen_id"];
					member.ParentMemberId = (int)row["parent_member_id"];
					member.Role.Id = (int)row["role_id"];

					network.Members.Add(member);
				}

				Error error = CitizenNetworksHandler.SaveCitizenNetwork(network, Mode == FAccessMode.Update);

				if (error != 0)
				{
					Utilities.ShowErrorDialog(error);
					return;
				}

				DialogResult = DialogResult.OK;
			}
		}

		private void BCancel_Click(object sender, EventArgs e)
		{
			DialogResult = DialogResult.Cancel;
		}

		private TCitizenNetworkRole GetSelectedRole(out int row_index)
		{
			row_index = 0;

			if (DataGridRoles.SelectedRows.Count == 0)
			{
				return null;
			}

			DataGridViewRow row = DataGridRoles.SelectedRows[0];

			row_index = row.Index;

			TCitizenNetworkRole role = new TCitizenNetworkRole()
			{
				Id = (int)row.Cells["colId"].Value,
				CitizenNetworkId = Id,
				Name = (string)row.Cells["colName"].Value,
				Description = (string)row.Cells["colDescription"].Value,
			};

			return role;
		}

		private void BAddRole_Click(object sender, EventArgs e)
		{
			TCitizenNetworkRole new_role = new TCitizenNetworkRole()
			{
				Id = 0,
				CitizenNetworkId = Id,
				Name = "",
			};

			RoleDlg.SetMode(FAccessMode.Create);
			RoleDlg.SetRole(new_role);

			if (RoleDlg.ShowDialog() == DialogResult.OK)
			{
				new_role = RoleDlg.GetRole();

				DTRoles.BeginLoadData();

				DataRow row = DTRoles.NewRow();

				//row["id"] = new_role.Id;
				row["citizennetwork_id"] = new_role.CitizenNetworkId;
				row["name"] = new_role.Name;
				row["description"] = new_role.Description;

				DTRoles.Rows.Add(row);

				DTRoles.EndLoadData();
			}
		}

		private void BEditRole_Click(object sender, EventArgs e)
		{
			int row_index;

			TCitizenNetworkRole role = GetSelectedRole(out row_index);

			if (role == null)
			{
				return;
			}

			RoleDlg.SetMode(FAccessMode.Update);
			RoleDlg.SetRole(role);

			if (RoleDlg.ShowDialog() == DialogResult.OK)
			{
				DataRow row = DTRoles.Rows[row_index];

				role = RoleDlg.GetRole();

				row.BeginEdit();

				row["id"] = role.Id;
				row["citizennetwork_id"] = Id;
				row["name"] = role.Name;
				row["description"] = role.Description;

				row.EndEdit();
			}
		}

		private void BReadRole_Click(object sender, EventArgs e)
		{
			int row_index;

			TCitizenNetworkRole role = GetSelectedRole(out row_index);

			if (role == null)
			{
				return;
			}

			RoleDlg.SetMode(FAccessMode.Read);
			RoleDlg.SetRole(role);
			RoleDlg.ShowDialog();
		}

		private void BDeleteRole_Click(object sender, EventArgs e)
		{
			int role_index;

			TCitizenNetworkRole role = GetSelectedRole(out role_index);

			if (role == null)
			{
				return;
			}

			// TODO: check the member isn't being used by no network member

			if (Utilities.ShowDeleteConfirmDialog("¿Desea eliminar el rol de la estructura?") != DialogResult.Yes)
			{
				return;
			}

			DTRoles.Rows.RemoveAt(role_index);
		}

		private TCitizenNetworkMember GetSelectedMember(out int row_index)
		{
			row_index = 0;

			if (DataGridMembers.SelectedRows.Count == 0)
			{
				return null;
			}

			DataGridViewRow row = DataGridMembers.SelectedRows[0];

			row_index = row.Index;

			TCitizenNetworkMember member = new TCitizenNetworkMember()
			{
				Id = (int)row.Cells["colId"].Value,
				CitizenNetworkId = Id,
				ParentMemberId = (int)row.Cells["colParentMemberId"].Value,

				Citizen = new TCitizen()
				{
					Id = (int)row.Cells["colCitizenId"].Value,
					Name = (string)row.Cells["colCitizenName"].Value,
				},

				Role = new TCitizenNetworkRole()
				{
					Id = (int)row.Cells["colRoleId"].Value,
					Name = (string)row.Cells["colRoleName"].Value
				}
			};

			return member;
		}

		private void BSelectLeadCitizen_Click(object sender, EventArgs e)
		{
			using (FCitizenList citizen_list = new FCitizenList())
			{
				citizen_list.SetMode(FAccessMode.Select);

				if (citizen_list.ShowDialog() == DialogResult.OK)
				{
					LeadCitizen = citizen_list.GetSelectedCitizen();

					TextBoxLeadCitizen.Text = $"{LeadCitizen.Name} {LeadCitizen.PaternalName} {LeadCitizen.MaternalName}";

					LLeadCitizenInfo.Text = $"Tel. {LeadCitizen.Phone}";
					if (LeadCitizen.PhoneExtension != "")
					{
						LLeadCitizenInfo.Text += $" Ext. {LeadCitizen.PhoneExtension}";
					}

					LLeadCitizenInfo.Text += $" Cel. {LeadCitizen.Cellphone}";

					RefreshMembersStructure();
				}
			}
		}

		private void BAddMember_Click(object sender, EventArgs e)
		{
			TCitizenNetworkMember member = new TCitizenNetworkMember();

			MemberDlg.SetMode(FAccessMode.Create);
			MemberDlg.SetMember(member);

			if (MemberDlg.ShowDialog() == DialogResult.OK)
			{
				member = MemberDlg.GetMember();

				DTMembers.BeginLoadData();

				DataRow row = DTMembers.NewRow();

				//row["id"] = member.Id;
				//row["id"] = (int)row["id"] + 1;
				row["citizennetwork_id"] = Id;
				row["parent_member_id"] = 0;
				row["citizen_id"] = member.Citizen.Id;
				row["citizen_name"] = member.Citizen.GetFullName();
				row["role_id"] = member.Role.Id;
				row["role_name"] = member.Role.Name;

				DTMembers.Rows.Add(row);

				DTMembers.EndLoadData();

				RefreshMembersStructure();
			}
		}

		private void BEditMember_Click(object sender, EventArgs e)
		{
			int selected_index;

			TCitizenNetworkMember member = GetSelectedMember(out selected_index);

			if (member == null)
			{
				return;
			}

			MemberDlg.SetMode(FAccessMode.Update);
			MemberDlg.SetMember(member);

			if (MemberDlg.ShowDialog() == DialogResult.OK)
			{
				member = MemberDlg.GetMember();

				DataRow row = DTMembers.Rows[selected_index];

				row.BeginEdit();

				row["id"] = member.Id;
				row["citizennetwork_id"] = Id;
				row["parent_member_id"] = member.ParentMemberId;
				row["citizen_id"] = member.Citizen.Id;
				row["citizen_name"] = member.Citizen.Name;
				row["role_id"] = member.Role.Id;
				row["role_name"] = member.Role.Name;

				row.EndEdit();

				RefreshMembersStructure();
			}
		}

		private void BReadMember_Click(object sender, EventArgs e)
		{
			int selected_index;

			TCitizenNetworkMember member = GetSelectedMember(out selected_index);

			if (member == null)
			{
				return;
			}

			MemberDlg.SetMode(FAccessMode.Read);
			MemberDlg.SetMember(member);
			MemberDlg.ShowDialog();
		}

		private void BDeleteMember_Click(object sender, EventArgs e)
		{
			int member_index;

			TCitizenNetworkMember member = GetSelectedMember(out member_index);

			if (member == null)
			{
				return;
			}

			// TODO: check the member doesn't have child members

			if (Utilities.ShowDeleteConfirmDialog("¿Desea eliminar el miembro de la estructura?") != DialogResult.Yes)
			{
				return;
			}

			DTMembers.Rows.RemoveAt(member_index);

			RefreshMembersStructure();
		}

		private void BPrint1x10_Click(object sender, EventArgs e)
		{
			// TODO: implement the 1x10 report
		}

		private void TreeViewMembers_ItemDrag(object sender, ItemDragEventArgs e)
		{
			DoDragDrop(e.Item, DragDropEffects.Move);
		}

		private void TreeViewMembers_DragEnter(object sender, DragEventArgs e)
		{
			e.Effect = DragDropEffects.Move;
		}

		private void TreeViewMembers_DragDrop(object sender, DragEventArgs e)
		{

		}

		private void DataGridMembers_SelectionChanged(object sender, EventArgs e)
		{

		}

		private void TreeViewMembers_DrawNode(object sender, DrawTreeNodeEventArgs e)
		{
			System.Drawing.Color background_color = SystemColors.Control;
			System.Drawing.Color foreground_color = SystemColors.WindowText;

			System.Drawing.Font font = e.Node.NodeFont ?? e.Node.TreeView.Font;

			if (e.Node == e.Node.TreeView.SelectedNode)
			{
				background_color = SystemColors.GradientInactiveCaption;
			}

			SolidBrush brush = new SolidBrush(background_color);

			e.Graphics.FillRectangle(brush, e.Bounds.X, e.Bounds.Y, TreeViewMembers.Width - (e.Bounds.X - TreeViewMembers.Location.X), e.Bounds.Height);
			TextRenderer.DrawText(e.Graphics, e.Node.Text, font, e.Bounds, foreground_color, TextFormatFlags.GlyphOverhangPadding);
		}

		private void TreeViewMembers_MouseClick(object sender, MouseEventArgs e)
		{
		}

		private void DataGridMembers_Click(object sender, EventArgs e)
		{
			// when a row of the members datagrid is selected the corresponding node on the treeview should also be selected
			int row_index;

			TCitizenNetworkMember member = GetSelectedMember(out row_index);

			if (member == null)
			{
				return;
			}

			foreach (TreeNode node in TreeViewUtilities.CollectTreeNodes(TreeViewMembers.Nodes))
			{
				if (node.Tag == null)
				{
					continue;
				}

				TCitizenNetworkMember? node_member = node.Tag as TCitizenNetworkMember;

				if (node_member == null)
				{
					continue;
				}

				if (node_member.Id == member.Id)
				{
					TreeViewMembers.SelectedNode = node;
					break;
				}
			}
		}

		private void TreeViewMembers_AfterSelect(object sender, TreeViewEventArgs e)
		{
			TreeNode node = TreeViewMembers.SelectedNode;

			if (node == null)
				return;

			if (node.Tag == null)
				return;

			TCitizenNetworkMember? node_member = node.Tag as TCitizenNetworkMember;

			if (node_member == null)
				return;

			//DataGridMembers.ClearSelection();

			foreach (DataGridViewRow row in DataGridMembers.Rows)
			{
				if ((int)row.Cells["colId"].Value == node_member.Id)
				{
					//if (row.Selected == false)
					//	row.Selected = true;
					DataGridMembers.CurrentCell = row.Cells["colCitizenName"];
					break;
				}
			}
		}

		private void BShowTree_Click(object sender, EventArgs e)
		{
			if (BShowTree.Checked)
			{
				splitContainer1.Panel2.Show();
				splitContainer1.Panel2Collapsed = false;
			}
			else
			{
				splitContainer1.Panel2Collapsed = true;
				splitContainer1.Panel2.Hide();
			}
		}
	}
}
